# Generated by Django 5.2.11 on 2026-03-03 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood', models.CharField(blank=True, default='', max_length=50)),
                ('summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('bot', 'Bot'), ('user', 'User')], max_length=10)),
                ('message_type', models.CharField(choices=[('greeting', 'Greeting'), ('mood_prompt', 'Mood Prompt'), ('mood_response', 'Mood Response'), ('reflection_prompt', 'Reflection Prompt'), ('reflection_response', 'Reflection Response'), ('acknowledgment', 'Acknowledgment')], max_length=30)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.dailychat')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailychat',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='one_chat_per_user_per_day'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('daily_chat', 'order'), name='unique_message_order_per_chat'),
        ),
    ]
