# Generated by Django 5.2.11 on 2026-03-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dailychat_chatmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychat',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('calm', 'Calm'), ('neutral', 'Neutral'), ('down', 'Down'), ('frustrated', 'Frustrated')], default='', max_length=50),
        ),
    ]
